### ISSUE TITLE
ReanimatedModule.installTurboModule is not a function

### ISSUE THREAD

**Issue by kokosky93** [craftzdog/react-native-checkbox-reanimated#5]
Hi,

Following error is beeing thrown when try to use that component

TypeError: ReanimatedModule.installTurboModule is not a function
at node_modules\expo\build\logs\LogSerialization.js:156:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync

+-- @babel/core@7.17.8
+-- @react-navigation/drawer@6.4.1
+-- @react-navigation/native@6.0.10
+-- @types/react@17.0.43
+-- @types/react-native@0.64.24
+-- @types/shortid@0.0.29
+-- expo@44.0.6
+-- expo-linking@3.0.0
+-- expo-status-bar@1.2.0
+-- moti@0.17.1
+-- native-base@3.3.10
+-- prettier@2.6.1
+-- react@17.0.1
+-- react-dom@17.0.1
+-- react-native@0.64.3
+-- react-native-checkbox-reanimated@0.1.1
+-- react-native-gesture-handler@2.3.2
+-- react-native-reanimated@2.5.0
+-- react-native-safe-area-context@4.2.4
+-- react-native-screens@3.13.1
+-- react-native-svg@12.3.0
+-- react-native-web@0.17.1
+-- shortid@2.2.16
+-- styled-components@5.3.5
+-- styled-system@5.1.5
`-- typescript@4.3.5

OS: Windows 10

It is a brand new project.

I am not sure how to fix it. Any suggestions?

**Comment by kokosky93** [comment]
okay this is related to incorrect packages for my expo package
